### ISSUE TITLE
URL to MVC Homework

### ISSUE THREAD

**Issue by gregorarb** [rstropek-teaching/contact-list-quiz-5ahif-gregorarb#2]
http://contactlist-mvc20171129105355.azurewebsites.net/

**Comment by rstropek** [comment]
@gregorarb Thank you for your homework. I tried to access it but did not succeed. A `GET http://contactlist-mvc20171129105355.azurewebsites.net/api/contacts` returns 404 (*Not Found*). Does it work for you?

Greetings,
Rainer Stropek.

**Comment by gregorarb** [comment]
@rstropek This is just the link to the Contact-List-Quiz solved with MVC (which can show all contacts, delete a contact and view details of a contact)

I created the link to the published RESTful Web-API in a different issue: http://contactlist22112017.azurewebsites.net/api/contacts

Greetings,
Gregor Arbeithuber.

**Comment by rstropek** [comment]
@gregorarb Ah, sorry. I did not recognize that. Now I could successfully test the RESTful Web API. Thank you for the clarification.

Greetings,
Rainer Stropek.
